// src/layouts/default.vue
<script setup lang="ts">
import { ref, watch } from "vue"
import { RouterLink, RouterView } from "vue-router"

import type { LinkProp } from "@/components/layout/side-nav.vue"
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import SideNav from "@/components/layout/side-nav.vue"
import UserNav from "@/components/layout/user-nav.vue"
import ThemeSwitcher from "@/components/layout/theme-switcher.vue"
import { useMediaQuery } from "@vueuse/core"

const defaultLayout = [15, 85]
const navPanelRef = ref<InstanceType<typeof ResizablePanel>>()
const navCollapsedSize = 4
const isCollapsed = ref(false)

function onCollapse() {
    isCollapsed.value = true
}

function onExpand() {
    isCollapsed.value = false
}

const isSmallScreen = useMediaQuery("(max-width: 1199px)")

watch(isSmallScreen, (n) => {
    if (n) navPanelRef.value?.collapse()
    else navPanelRef.value?.expand()
})

const links: LinkProp[] = [
    {
        title: "Contents",
        icon: "lucide:file-search-2",
        link: "/contents",
    },
    {
        title: "Create Content",
        icon: "lucide:file-plus",
        link: "/contents/create",
    },
]
</script>

<template>
    <div class="flex flex-col">
        <!-- top nav -->
        <div class="border-b">
            <div class="flex h-16 items-center px-4">
                <nav class="flex items-center space-x-4 lg:space-x-6)">
                    <h1 class="text-4xl"><RouterLink to="/">Optimus</RouterLink></h1>
                    <Separator :decorative="true" orientation="vertical" class="h-10" />
                    <RouterLink
                        activeClass="text-primary"
                        to="/overview"
                        class="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
                    >
                        Overview
                    </RouterLink>
                    <RouterLink
                        to="/about"
                        activeClass="text-primary"
                        class="text-sm font-medium text-muted-foreground transition-colors hover:text-primary"
                    >
                        About
                    </RouterLink>
                </nav>
                <div class="ml-auto flex items-center space-x-4">
                    <ThemeSwitcher />
                    <UserNav />
                </div>
            </div>
        </div>

        <div class="flex">
            <!-- side bar -->
            <ResizablePanelGroup
                id="resize-panel-group-1"
                direction="horizontal"
                class="h-full min-h-[calc(100vh-4.0625rem)] items-stretch"
            >
                <ResizablePanel
                    ref="navPanelRef"
                    id="resize-panel-1"
                    :default-size="defaultLayout[0]"
                    :collapsed-size="navCollapsedSize"
                    collapsible
                    :min-size="13"
                    :max-size="20"
                    class="transition-all duration-300 ease-in-out"
                    :class="cn(isCollapsed && 'min-w-[50px]')"
                    @expand="onExpand"
                    @collapse="onCollapse"
                >
                    <SideNav :is-collapsed="isCollapsed" :links="links" />
                </ResizablePanel>
                <ResizableHandle
                    id="resize-handle-1"
                    with-handle
                    @click="
                        navPanelRef?.isCollapsed ? navPanelRef?.expand() : navPanelRef?.collapse()
                    "
                />

                <ResizablePanel id="resize-panel-3" :default-size="defaultLayout[1]">
                    <!-- Content -->
                    <div class="custom-scrollbar p-4 h-full overflow-y-auto">
                        <RouterView />
                    </div>
                </ResizablePanel>
            </ResizablePanelGroup>
        </div>
    </div>
</template>

// src/layouts/default.tsx
import { useState, useRef, useEffect, type ReactElement } from "react"
import { Link, useRouter } from "@tanstack/react-router"
import { useMediaQuery } from "@uidotdev/usehooks"
import type { ImperativePanelHandle } from "react-resizable-panels"
import { ResizableHandle, ResizablePanel, ResizablePanelGroup } from "@/components/ui/resizable"
import { Separator } from "@/components/ui/separator"
import { cn } from "@/lib/utils"
import SideNav from "@/components/layout/side-nav"
import UserNav from "@/components/layout/user-nav"
import { ThemeSwitcher } from "@/components/layout/theme-switcher"

const defaultLayout = [15, 85]
const navCollapsedSize = 4

const links = [
    {
        title: "Contents",
        icon: "lucide:file-search-2",
        link: "/contents",
    },
    {
        title: "Create Content",
        icon: "lucide:file-plus",
        link: "/contents/create",
    },
]

export function DefaultLayout({ children }: { children: ReactElement }) {
    const [isCollapsed, setIsCollapsed] = useState(false)
    const navPanelRef = useRef<ImperativePanelHandle>(null)
    const isSmallScreen = useMediaQuery("(max-width: 1199px)")
    const router = useRouter()

    const onCollapse = () => setIsCollapsed(true)
    const onExpand = () => setIsCollapsed(false)

    useEffect(() => {
        if (isSmallScreen) navPanelRef.current?.collapse()
        else navPanelRef.current?.expand()
    }, [isSmallScreen])

    useEffect(() => {
        const handleKeyDown = (e: KeyboardEvent) => {
            if (e.key === "[") navPanelRef.current?.collapse()
            if (e.key === "]") navPanelRef.current?.expand()
        }
        window.addEventListener("keydown", handleKeyDown)
        return () => window.removeEventListener("keydown", handleKeyDown)
    }, [])

    return (
        <div className="flex flex-col">
            <div className="border-b">
                <div className="flex h-16 items-center px-4">
                    <nav className="flex items-center space-x-4 lg:space-x-6">
                        <h1 className="text-4xl">
                            <Link to="/">Optimus</Link>
                        </h1>
                        <Separator decorative orientation="vertical" className="h-10" />
                        <Link
                            to="/overview"
                            className={cn(
                                "text-sm font-medium text-muted-foreground transition-colors hover:text-primary",
                                router.state.location.pathname === "/overview" && "text-primary",
                            )}
                        >
                            Overview
                        </Link>
                        <Link
                            to="/about"
                            className={cn(
                                "text-sm font-medium text-muted-foreground transition-colors hover:text-primary",
                                router.state.location.pathname === "/about" && "text-primary",
                            )}
                        >
                            About
                        </Link>
                    </nav>
                    <div className="ml-auto flex items-center space-x-4">
                        <ThemeSwitcher />
                        <UserNav />
                    </div>
                </div>
            </div>

            <div className="flex">
                <ResizablePanelGroup
                    direction="horizontal"
                    className="h-full min-h-[calc(100vh-4.0625rem)] items-stretch"
                >
                    <ResizablePanel
                        ref={navPanelRef}
                        defaultSize={defaultLayout[0]}
                        collapsedSize={navCollapsedSize}
                        collapsible
                        minSize={13}
                        maxSize={20}
                        onCollapse={onCollapse}
                        onExpand={onExpand}
                        className={cn(
                            "transition-all duration-300 ease-in-out",
                            isCollapsed && "min-w-[50px]",
                        )}
                    >
                        <SideNav isCollapsed={isCollapsed} links={links} />
                    </ResizablePanel>
                    <ResizableHandle
                        withHandle
                        onClick={() =>
                            navPanelRef.current?.isCollapsed
                                ? navPanelRef.current?.expand()
                                : navPanelRef.current?.collapse()
                        }
                    />
                    <ResizablePanel defaultSize={defaultLayout[1]}>
                        <div className="custom-scrollbar p-4 h-full overflow-y-auto max-h-[calc(100vh-65px)]">
                            {children}
                        </div>
                    </ResizablePanel>
                </ResizablePanelGroup>
            </div>
        </div>
    )
}
