// src/components/ui/kbd/kbd.vue
<script setup lang="ts">
import { cn } from "@/lib/utils"
import type { HTMLAttributes } from "vue"

const props = defineProps<{
    class?: HTMLAttributes["class"]
}>()
</script>

<template>
    <kbd
        :class="
            cn(
                'inline-flex items-center rounded-sm border px-2.5 py-0.5 text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 text-foreground',
                props.class,
            )
        "
    >
        <slot />
    </kbd>
</template>

// src/components/ui/kbd.tsx
import React from "react"
import { cn } from "@/lib/utils"

interface KbdProps extends React.HTMLAttributes<HTMLElement> {
    className?: string
}

const Kbd: React.FC<KbdProps> = ({ className, children, ...props }) => {
    return (
        <kbd
            className={cn(
                "inline-flex items-center rounded-sm border px-2.5 py-0.5 text-sm font-semibold transition-colors focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2 text-foreground",
                className,
            )}
            {...props}
        >
            {children}
        </kbd>
    )
}

export default Kbd
